# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-21 12:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_tasker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskqueue',
            name='back_off_base_seconds',
            field=models.PositiveSmallIntegerField(default=60),
        ),
        migrations.AddField(
            model_name='taskqueue',
            name='back_off_max_seconds',
            field=models.PositiveIntegerField(default=86400),
        ),
        migrations.AddField(
            model_name='taskqueue',
            name='back_off_multiplier',
            field=models.FloatField(default=4),
        ),
    ]
