# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-02 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_tasker', '0003_auto_20161225_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskinfo',
            name='eta',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='taskinfo',
            name='retry_count',
            field=models.PositiveSmallIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='taskinfo',
            name='ts',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterIndexTogether(
            name='taskinfo',
            index_together=set([('id', 'eta', 'status'), ('id', 'target'), ('target', 'status'), ('target', 'eta')]),
        ),
    ]
