# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-20 11:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_tasker', '0005_auto_20170107_2302'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='taskinfo',
            index_together=set([('id', 'eta', 'status'), ('id', 'target'), ('target', 'eta'), ('id', 'target', 'status', 'eta'), ('target', 'status')]),
        ),
    ]
