# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 13:26
from __future__ import unicode_literals

from django.db import migrations, models
import django_tasker.models


class Migration(migrations.Migration):

    dependencies = [
        ('django_tasker', '0006_auto_20170120_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskinfo',
            name='status',
            field=models.IntegerField(choices=[(0, 'Created'), (1, 'Queued'), (2, 'Eager'), (3, 'Retry'), (4, 'Busy'), (5, 'Success'), (6, 'Błąd'), (7, 'Corrupted')], default=django_tasker.models.TaskStatus(0)),
        ),
    ]
