# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-12 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_tasker', '0007_auto_20170505_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskinfo',
            name='name',
            field=models.CharField(blank=True, max_length=300, null=True, unique=True),
        ),
    ]
