# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-12 20:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_tasker', '0008_taskinfo_name'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='taskinfo',
            index_together=set([('status', 'eta'), ('target', 'status'), ('id', 'target', 'status', 'eta'), ('target', 'eta'), ('id', 'target'), ('id', 'eta', 'status')]),
        ),
    ]
