# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-09 13:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_tasker', '0010_auto_20170523_1554'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='taskinfo',
            index_together=set([('id', 'target'), ('status', 'eta', 'target'), ('id', 'target', 'status', 'eta'), ('status', 'eta'), ('target', 'eta'), ('status', 'ts'), ('id', 'eta', 'status'), ('target', 'status')]),
        ),
    ]
