# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-09 18:20
from __future__ import unicode_literals

from django.db import migrations, models
import django_tasker.models


class Migration(migrations.Migration):

    dependencies = [
        ('django_tasker', '0011_auto_20170609_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskinfo',
            name='status',
            field=models.IntegerField(choices=[(0, 'Created'), (1, 'Queued'), (2, 'Eager'), (3, 'Retry'), (4, 'Busy'), (5, 'Success'), (6, 'Error'), (7, 'Corrupted')], db_index=True, default=django_tasker.models.TaskStatus(0)),
        ),
        migrations.AlterIndexTogether(
            name='taskinfo',
            index_together=set([('status', 'eta', 'target'), ('status', 'ts'), ('target', 'eta'), ('status', 'eta', 'target', 'id'), ('status', 'eta'), ('target', 'status')]),
        ),
    ]
