language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"

sudo: false

cache:
  - apt
  - pip

install:
  - pip install -r requirements.txt -r requirements-dev.txt

script: coverage run runtests.py

after_success:
  - coveralls
  - bash <(curl -s https://codecov.io/bash)

branches:
  only:
    - develop
    - master

