language: python

python:
  - "3.5"
  - "3.4"

sudo: false

cache:
  - apt
  - pip

install:
  - pip install -r requirements-dev.txt

script: coverage run runtests.py
after_success:
  - coveralls
  - bash <(curl -s https://codecov.io/bash)

branches:
  only:
    - develop
    - master

